### ISSUE TITLE
No CPUE leads to error and confusion in SS_readdat

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [r4ss/r4ss#362]
https://github.com/r4ss/r4ss/blob/b90113ad2819bb5d183b0caf7b238f667863c87f/R/SS_readdat.R#L254

I was investigating a model with zero CPUE observations and ...
`SS_readdat` errors because `1:nrow(datlist$CPUE)` is equivalent to `1:NULL`

I thought about changing it to `1:NROW(datlist$CPUE)` but this leads to an error in the next line because `datlist$CPUE[j,]` doesn't exist. So that won't work. Instead, I think we can use `if(!is.null(nrow(datlist$CPUE))){ ... }` around the call here on line 254 and the one that precedes it on line 113 for versions other than 3.3. 

Then, looking at a model with CPUE, I noticed that there are instances that the sum of `datlist$NCPUEObs` will not be equal to `datlist$N_cpue` because the latter takes into account negative fleet observations where the former does not. I am not sure which behaviour is beneficial, just noting it here to discuss.

Bug also on https://github.com/r4ss/r4ss/blob/b90113ad2819bb5d183b0caf7b238f667863c87f/R/SS_readdat.R#L166 because `NROW(datlist$CPUE)` leads to a value of 1, where `nrow()` would lead to an error here. I think we can use an `ifelse()` statement.
```
datlist$N_cpue <- ifelse(is.na(datlist$CPUE[1]), 0, NROW(datlist$CPUE))
```

**Comment by iantaylor-NOAA** [comment]
Anything wrong with just wrapping the CPUE calcs within a test for non-null CPUE?
```
if(!is.null(datlist$CPUE)){
   ...
}
```
It looks like the `SS_readdat_3.24` and `SS_readdat_3.30` differ in one returning NULL and the other NA. I would change the 3.30 version to remove these lines that convert from NULL to NA unless that serves some other purpose:
https://github.com/r4ss/r4ss/blob/development/R/SS_readdat_3.30.R#L301-L303

**Comment by k-doering-NOAA** [comment]
https://github.com/r4ss/r4ss/pull/361/commits/ae3c61ce78a640783ecc8998dddd42e18898c3d1 in PR #361 has a fix for this, but I'm sure it is added as @kellijohnson-NOAA and @iantaylor-NOAA suggest. Feel free to make changes to the PR or I can make them if that is easier.

**Comment by kellijohnson-NOAA** [comment]
It would be good if they both returned NULL.

**Comment by iantaylor-NOAA** [comment]
@kellijohnson-NOAA this should now be fixed thanks to PR #361. Please let us know if it doesn't work.

**Comment by kellijohnson-NOAA** [comment]
The models read in now with the fixes, thanks @k-doering-NOAA. I still get `is.na(output$cpue))` as a true value though. I think that if it is NULL in `SS_readdat` that it should also be NULL in `SS_output` or is my logic failed? Would there be any downstream dependency that would be wrecked if we changed SS_output on line 2580 to be NULL instead of NA? I did it locally and was still able to run `SS_plots()` on the output just fine. It just doesn't generate an index tab.

Side note - the fix that @k-doering-NOAA generated clearly illustrates why we should be using `list[["nameofelement"]]` rather than `list$nameofelement` as a best practice for all of the packages that we contribute to. Partial matching is a real pain.

**Comment by iantaylor-NOAA** [comment]
Sorry, I hadn't realized it was an issue in SS_output and not just SS_readdat_3.30.
I jushed pushed the NA to NULL change in commit c1cfbe0d165b0367cff7d40f46b26a8587e441fd.

Changing to `list[["nameofelement"]]` could be a pain, but I appreciate the need.

**Comment by kellijohnson-NOAA** [comment]
Thanks for the fixes.
To be clear, I wasn't really advocating for changing the code for the partial matching problem, but rather, it was just a note for those writing future code.
