### ISSUE TITLE
relative spawning biomass plots expected value and CI's are different

### ISSUE THREAD

**Issue by k-doering-NOAA** [r4ss/r4ss#566]
I think maybe the CI's are not being calculated correctly? Using [this model](https://github.com/nmfs-stock-synthesis/user-examples/tree/main/model_files/simple_long) and ss3 v 3.30.18.

![screenshot of relative spawning biomass](https://user-images.githubusercontent.com/48930335/140079774-8ce2114a-5a7e-43ff-8659-d2f7d5f9fe54.png)

**Comment by chantelwetzel-noaa** [comment]
Having worked on this section of the code recently, I suspect the actual issue is due to using option 2, Depletion basis:  2=rel SPBmsy, where the code that creates the plot is not grabbing the SPBmsy and dividing the relative spawning biomass by this value.  I would recommend looking at the changes done in the "depl_basis_plot" branch which deals with  other depletion scaling issues when creating this figure.  If we can ensure the existing changes in the "depl_basis_plot" branch are robust to various model versions, I think adding a fix for the SPBmsy should be relatively easy.

**Comment by k-doering-NOAA** [comment]
Thanks @chantelwetzel-noaa! This model is using depletion option 2, I will look more into it!

**Comment by iantaylor-NOAA** [comment]
I can help with this tomorrow but @k-doering-NOAA, I welcome you looking into it more.

I thought this was all resolved in https://github.com/r4ss/r4ss/issues/5, but clearly not.

`SSplotTimeseries()` may need a change similar to this recent change in `SSplotSPR()`, https://github.com/r4ss/r4ss/commit/c07f0bd0ad58775dc21df35c9dd561a5780c4574, where the `btarg` and `sprtarg` inputs specified in the forecast file aren't relevant when for some starter file options related to Depletion basis and SPR report basis.

**Comment by k-doering-NOAA** [comment]
Thanks @chantelwetzel-noaa and @iantaylor-NOAA , I finally tried out the depl_basis_plot branch and the plots now look like this:
![image](https://user-images.githubusercontent.com/48930335/144633116-731beab0-76ed-45a8-9b6f-1b4198608e49.png)

I still don't understand why the first plot has different values than the second, though?

**Comment by chantelwetzel-noaa** [comment]
Looking at these plots, my guess is that the first without uncertainty is still not grabbing the correct denominator, while the plot with uncertainty is.  I can take a look at the code in this branch to see where the issue may be.

**Comment by k-doering-NOAA** [comment]
Thanks @chantelwetzel-noaa ! The change in https://github.com/r4ss/r4ss/commit/382bcd0b95ee96d0288863c0c35bb73600564d82 fixed the issue:

![image](https://user-images.githubusercontent.com/48930335/144862047-4b180f4d-7ded-49ea-a87c-e4cb66e42c23.png)

It would be great to open a PR to main for this branch

**Comment by iantaylor-NOAA** [comment]
As discussed in Pull Request #580, this still needs work for multi-area models with depletion basis relative to something other than B0. Figures below show a mismatch between the total relative spawning output plot and the area-specific plot (top plot starts at ~3.5, lower at 1.0). However, B/Bmsy doesn't make sense on an area-specific basis, at least as formulated in Stock Synthesis. 

Unless someone has another suggestions, I think it makes sense to make the area-specific plot relative to B0 as it is now and just change y-axis label and caption to reflect that.

![image](https://user-images.githubusercontent.com/4992918/145291685-34f6cb3e-3bb7-4f1e-80f9-9a4b227de925.png)
