### ISSUE TITLE
[Bug]: Excessive warnings in `SS_write()`

### ISSUE THREAD

**Issue by okenk** [r4ss/r4ss#912]
### Describe the bug

I recently updated {r4ss}. Now, when I use `SS_write()` I often get warnings about {r4ss} making an assumption about the parfile name. The model list has par = NULL, and I am not starting from the par file. The warnings are gumming up my workflow a bit.

I was wondering how you would recommend making these warnings go away?

### To Reproduce

For example, [this code](https://github.com/pacific-hake/ss3roms/blob/main/R/cod_OM.R#L113-L143) leads to >50 warnings, but as far as I can tell, there is no cause for concern.

### Expected behavior

I would like the warnings to go away if the par file is null and not being used as starting values. Maybe we could add a `par` argument to `SS_write()` so that it doesn't always insist on writing the par file. My preference would be for this to default to `FALSE` because personally I don't think I would want it to be `TRUE` very often, but any ability to turn off writing of the par file, and thus the warnings, would be sufficient.

Alternatively, {r4ss} could suppress the warnings if the par file is not being used to run the model.

### Which OS are you seeing the problem on?

Linux

### Which versions of r4ss and SS3 are you seeing the problem on?

r4ss version 1.49.1, SS3 version V3.30.22.1

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/r4ss/r4ss#code-of-conduct)

**Comment by okenk** [comment]
Another related issue that I had is I wrote an {ss3sim} operating model using `SS_write()`, which wrote an (unnecessary) par file ss3.par.

Then, ss3sim copied the whole base model directory into each sub-directory where stock synthesis was being simulated and estimated. However, ss3sim called an executable "ss." Thus, each directory (of which there were hundreds), had two par files. `SS_output()` selects ss3.par over ss.par. However, ss3.par was an empty file written by `SS_write()`, not the par file from the actual model run.

**Comment by e-perl-NOAA** [comment]
@iantaylor-NOAA maybe this is where we should modify the SS_write file - it may be creating a ss3.par file even if you aren't specifying for a par file. Might be able to delete that bit altogether?
https://github.com/r4ss/r4ss/blob/76ef50038cf134c8f64d49be5119af3f3ebd2d37/R/SS_write.R#L119-L125

**Comment by e-perl-NOAA** [comment]
@okenk I'm sorry for the frustration with the ss3.par file (I appreciate your frustrated comments in your code that you attached in the issue, that's definitely something I would do in my code haha), we had to make those changes to keep up with ss3 changes that are now writing a ss3.par file instead of a ss.par file. Most of the changes in r4ss were easy but I/we thought that the SS_write() function might prove more difficult to change since we wanted to have backward compatibility and try to alert/motivate/force people to be aware of now using ss3.par instead of ss.par. 

1. Could you possibly send a copy (either copy and paste in a comment or attach a text file) of all the warnings that you are getting? Would be nice to see them so that we can see if there are any other warnings that we should try to get rid of if they aren't useful.
2. Can you show me where ss3sim seems to be calling a ss executable instead of a ss3 executable? We will just want to make sure we work with Kelli to get that updated since we have moved over to using the `ss3` notation for most things instead of `ss`.
3. Have you updated your ss3 executable to the new 3.30.22.1 release?

**Comment by okenk** [comment]
1. It is running as we speak, but I am pretty sure the excessive warning was:
```
parfile name assumed to be 'ss3.par' because it was not specified by a recent version of SS_write()
```
I agree it is probably good to alert people to that if it is going to make an assumption, but when the par slot is `NULL` in the r4ss list, and it is not being used for starting values (i.e., `init_values_src = 0`), it seems preferable to just not write a par file at all.

2. ss3sim calls an executable called ss3 (see [here](https://github.com/ss3sim/ss3sim/blob/main/R/ss3sim_base.r#L514-L522) and [here](https://github.com/ss3sim/ss3sim/blob/main/R/get_bin.R#L21)), but it currently has a 2022 version of stock synthesis in the repo, which Kelli knows is out of date. I have been getting weird results myself that are related to the SS3 version (see item 3), so have been using 2022, 2023, and 2024 SS3 releases at various points, which I am changing in and out myself.

3. I have been alternating between a lot of versions of r4ss and SS3 because of both some weird index behavior in SS3, and the issues with the par file in r4ss. @iantaylor-NOAA and I finally got to the bottom of the index issues, and I am now using the 3.30.22.1 release and the latest commit from r4ss.

**Comment by iantaylor-NOAA** [comment]
@okenk, Sorry about this.  This is 100% my fault due to creating the warning when `is.null()` instead of `!is.null()`. It should be fixed in d424c32 which I just pushed directly to main. Please let me know if you update r4ss and have any further issues. Otherwise, go ahead and close this issue once you've confirmed it's working.

**Comment by okenk** [comment]
Ahhh, this makes perfect sense now. Yes, no more warnings or double par files in directories. Thank you!

**Comment by okenk** [comment]
I am still having some trouble with this. 
1. The code was correct in the first place. You want to name the par file ss3.par if the name IS null. If the name is NOT null, you should keep the name as it is.
2. This fixed my old problems, however, because it forced {r4ss} to completely ignore the par file, which is the behavior I wanted. 
3. I think it would help to be more aggressive with `SS_write()` not messing with the par file. I suggest changing [this line](https://github.com/r4ss/r4ss/blob/main/R/SS_write.R#L118C3-L118C35) from `if ("par" %in% names(inputlist))` to `if (!is.null(intputlist[[par]])`. As it stands, par is currently ALWAYS in the names of `inputlist`. Sometimes it is empty.

**Comment by iantaylor-NOAA** [comment]
@okenk, sorry for the confusion and lingering issue. 

How about this flow for `SS_read()` and `SS_write()` and taking all the warnings away (except in the case where `SS_read()` sees two different .par files in the same folder)?
In the rare case where you have a non-NULL $par object in the list that doesn't have $par$parfile defined then it will just set `parfile <- "ss3.par"` without a warning.

```mermaid
graph TD;
    A[run SS_read] --> B{starter file\nspecifies that\nmodel uses .par};
    B --> |yes| C[read .par file];
    B --> |no| D[ignore .par file];
    C --> G[SS_write writes $par to parfile];
    C --> |user sets $par <- NULL| F[SS_write writes .par file];
    D --> F[SS_write doesn't write .par file];
```

**Comment by okenk** [comment]
I like this workflow, but I think you still need to make the change I recommended in (3). 

If the user sets `$par <- NULL`, then `SS_write()` will check if `$par$parfile` is `NULL`. If it `NULL`, the function will set `$par$parfile <- 'ss3.par'`. Now, `$par` is no longer `NULL`, so the par file will get written as a blank document called ss3.par.

**Comment by kellijohnson-NOAA** [comment]
How would you know that the file is supposed to be named "ss3.par" though because you can name the .par file anything you want if you change the command to run the executable with that option or if you name the executable something different.

**Comment by okenk** [comment]
You wouldn't, but if there is no name provided, [`SS_write()` defaults to ss3.par](https://github.com/r4ss/r4ss/blob/main/R/SS_write.R#L119-L120).

**Comment by iantaylor-NOAA** [comment]
> I like this workflow, but I think you still need to make the change I recommended in (3).
> 
> If the user sets `$par <- NULL`, then `SS_write()` will check if `$par$parfile` is `NULL`. It will be `NULL`, so the function will set `$par$parfile <- 'ss3.par'`. Now, `$par` is no longer `NULL`, so the par file will get written as a blank document called ss3.par.

Yes, definitely. I just wanted feedback on the plan before making the change.

> How would you know that the file is supposed to be named "ss3.par" though because you can name the .par file anything you want if you change the command to run the executable with that option or if you name the executable something different.

Users could also modify the $par$parfile variable to write to a different filename than what it was read from.
